SELECT * 
FROM SUBJECT;

SELECT *
FROM SUBJECT
WHERE SUB_GRADE IN ('1', '3')
ORDER BY SUB_GRADE DESC, SUB_NO;

SELECT *
FROM SUBJECT
WHERE SUB_NAME LIKE '%설계%';

SELECT *
FROM SUBJECT
WHERE SUB_NO >= 105
ORDER BY SUB_NO ASC;

INSERT INTO SUBJECT(SUB_NO, SUB_NAME, SUB_PROF)
VALUES('201','자바','홍길동');

INSERT INTO SUBJECT(SUB_NO, SUB_NAME, SUB_PROF, SUB_GRADE, SUB_DEPT)
VALUES('202','오라클','박영희','1','컴퓨터정보');
COMMIT;

UPDATE SUBJECT
SET 
    SUB_GRADE = 2,
    SUB_DEPT = '컴퓨터정보'
WHERE SUB_NO = 201;
COMMIT;

DELETE FROM SUBJECT WHERE SUB_NO >=200;
COMMIT;

ROLLBACK;
    
    





