-- 그룹 함수

SELECT MAX(STU_HEIGHT)AS MAX_HEIGHT
FROM STUDENT;

SELECT AVG(STU_HEIGHT) AS "키 평균"
FROM STUDENT;

SELECT SUM(STU_HEIGHT)
FROM STUDENT;

SELECT STU_NAME 이름 FROM STUDENT;
SELECT STU_NAME AS 이름 FROM STUDENT;