-- STUDENT
-- 각 학과의 가장 큰 사람을 구해라 - 학번, 이름, 키

SELECT STU_DEPT, MAX(STU_HEIGHT) 
FROM STUDENT
GROUP BY STU_DEPT;

SELECT T.STU_DEPT, T.MAX_HEIGHT, STU_NAME, STU_NO
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, MAX(STU_HEIGHT) MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
) T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT;

-- 1. 각 직급별 가장 많은 급여를 받는 교수의 이름, 급여 출력 (professor)
SELECT POSITION, MAX(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT NAME, P.POSITION, T.MAX_PAY
FROM PROFESSOR P
INNER JOIN (
    SELECT POSITION, MAX(PAY) AS MAX_PAY
    FROM PROFESSOR
    GROUP BY POSITION
) T ON P.POSITION = T.POSITION AND P.PAY = T.MAX_PAY;

-- 2. 본인 부서의 평균 급여보다 높은 급여를 받는 사워의 사번, 이름, 급여 출력 (emp)

SELECT DEPTNO, ROUND(AVG(SAL), 2) AVG_SAL
FROM EMP
GROUP BY DEPTNO;

SELECT E.DEPTNO, EMPNO, ENAME, E.SAL, AVG_SAL
FROM EMP E
INNER JOIN (
    SELECT DEPTNO, ROUND(AVG(SAL), 2) AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO AND E.SAL > T.AVG_SAL
ORDER BY DEPTNO;




