SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;

-- 닉네임, 작성한 게시글 개수 출력

SELECT NICKNAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

SELECT NICKNAME, COUNT(BOARDNO) COMMENT_NUMBER
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY NICKNAME;

-- 각 게시글의 제목, 댓글 개수 출력 : TITLE AND NUMBER OF EACH POST

SELECT B.BOARDNO, TITLE, COUNT(COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE;

-- 게시글 번호, 게시글 제목, 내용, 작성일, 작성자 닉네임, 댓글 개수 (없으면 0) 추력

SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;


SELECT B.BOARDNO, NICKNAME, B.TITLE, B.CONTENTS, COUNT(COMMENTNO) AS 댓글개수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.BOARDNO, NICKNAME, B.TITLE, B.CONTENTS
ORDER BY BOARDNO;

-- CASE ~ WHEN
-- PROFESSOR
-- 1. PROFESSOR 테이블에서 400이상의 급여를 받으면 , A
-- 300~400 사이면 B, 나머지는 C로 출력
--  교수 이름, 급여 등급 (A~C)
SELECT NAME, PAY,
    CASE
        WHEN PAY >= 400 THEN 'A'
        WHEN PAY BETWEEN 300 AND 400 THEN 'B'
        ELSE 'C'
    END 등급
FROM PROFESSOR;

SELECT * FROM PROFESSOR;



