-- CASE - WHEN : A BIT MORE COMPLEX THAN DECODE
SELECT * FROM PROFESSOR;
SELECT 
    PAY,
    CASE
        WHEN PAY >= 500 THEN '고소득'
        WHEN PAY BETWEEN 300 AND 500 THEN '적당히 받음'
        ELSE '화이팅'
    END 급여정보
FROM PROFESSOR; 
