SELECT * FROM STUDENT;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES('12341234', '홍길동','게계');

INSERT INTO STUDENT
VALUES('12345678', '김철수', '전기전자', 1, 'A', 'M', 175, NULL);

ROLLBACK;